# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create a natural causal list from a DBN. This is the C++ backend of the function.
#' 
#' @param cl an initialized causality list
#' @param net a dbn object treated as a list of lists
#' @param ordering a vector with the names of the variables in order
#' @return the natCauslist equivalent to the DBN
create_natcauslist_cpp <- function(cl, net, ordering) {
    .Call('_natPsoho_create_natcauslist_cpp', PACKAGE = 'natPsoho', cl, net, ordering)
}

#' Create a matrix with the arcs defined in a causlist object
#' 
#' @param cl a causal list
#' @param ordering a list with the order of the variables in t_0
#' @param rows number of arcs in the network
#' @return a StringMatrix with the parent nodes and the children nodes
cl_to_arc_matrix_cpp <- function(cl, ordering, rows) {
    .Call('_natPsoho_cl_to_arc_matrix_cpp', PACKAGE = 'natPsoho', cl, ordering, rows)
}

#' Add a velocity to a position
#' 
#' @param cl the position's causal list
#' @param vl the velocity's positive causal list
#' @param vl_neg velocity's negative causal list
#' @param n_arcs number of arcs present in the position. Remainder: can't return integers by reference, they get casted to 1 sized vectors
#' @return the new position by reference and the new number of arcs by return
nat_pos_plus_vel_cpp <- function(cl, vl, vl_neg, n_arcs) {
    .Call('_natPsoho_nat_pos_plus_vel_cpp', PACKAGE = 'natPsoho', cl, vl, vl_neg, n_arcs)
}

#' Initialize the particles
#' 
#' @param nodes the names of the nodes
#' @param size the size of the DBN
#' @param n_inds the number of particles
#' @return a list with the randomly initialized particles
init_list_cpp <- function(nodes, size, n_inds) {
    .Call('_natPsoho_init_list_cpp', PACKAGE = 'natPsoho', nodes, size, n_inds)
}

#' One-hot encoder for natural numbers without the 0
#' 
#' Given a natural number, return the natural number equivalent to its
#' one-hot encoding. Instead of pow, the '<<' operator will be used.
#' Examples: 3 -> 100 -> 4, 5 -> 10000 -> 16
#' @param nat the natural number to convert
#' @return the converted number
one_hot_cpp <- function(nat) {
    .Call('_natPsoho_one_hot_cpp', PACKAGE = 'natPsoho', nat)
}

debug_cpp <- function() {
    .Call('_natPsoho_debug_cpp', PACKAGE = 'natPsoho')
}

#' Substracts two Positions to obtain the Velocity that transforms one into the other
#' 
#' @param cl the first position's causal list
#' @param ps the second position's causal list
#' @param vl the Velocity's causal list
#' @return a list with the Velocity's causal list and the number of operations
pos_minus_pos_cpp <- function(cl, ps, vl) {
    .Call('_natPsoho_pos_minus_pos_cpp', PACKAGE = 'natPsoho', cl, ps, vl)
}

#' Adds two natVelocities 
#' 
#' Adds two natVelocities represented as two numeric vectors: one with the
#' positive part and one with the negative part. Adding them is a process that
#' does a bitwise 'or' with both the positive and negative parts of the two
#' velocities, adjusts the new abs_op, removes duplicated arcs in the final
#' velocity by using a bitwise 'xor' with both parts and adjusts the final abs_op.
#' The results are returned via modifying the original vl1 and vl1_neg by
#' reference and returning the final abs_op normally. I can't have an integer
#' edited by reference because it automatically gets casted and cannot be used
#' to return values. 
#' 
#' @param vl1 the first Velocity's positive part 
#' @param vl1_neg the first Velocity's negative part 
#' @param vl2 the second Velocity's positive part
#' @param vl2_neg the first Velocity's negative part 
#' @param abs_op1 the number of {1,-1} operations in the first velocity
#' @param abs_op2 the number of {1,-1} operations in the second velocity
#' @return the total number of resulting operations
nat_vel_plus_vel_cpp <- function(vl1, vl1_neg, vl2, vl2_neg, abs_op1, abs_op2) {
    .Call('_natPsoho_nat_vel_plus_vel_cpp', PACKAGE = 'natPsoho', vl1, vl1_neg, vl2, vl2_neg, abs_op1, abs_op2)
}

#' Multiply a Velocity by a constant real number
#' 
#' @param k the constant real number
#' @param vl the Velocity's positive causal list
#' @param vl_neg the Velocity's negative causal list
#' @param abs_op the final number of {1,-1} operations
#' @param max_size the maximum size of the network
#' @return the new total number of operations 
nat_cte_times_vel_cpp <- function(k, vl, vl_neg, abs_op, max_size) {
    .Call('_natPsoho_nat_cte_times_vel_cpp', PACKAGE = 'natPsoho', k, vl, vl_neg, abs_op, max_size)
}

